# Generated by Django 3.2.6 on 2021-09-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conexs_pool_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('Posgresql', 'Posgresql'), ('Mysql', 'Mysql'), ('SqlServer', 'SqlServer')], max_length=255)),
                ('puerto', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipBetweenTableConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=255)),
                ('conexs_pool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_field.conexs_pool_field')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipBetweenTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=8000)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_field.relationshipbetweentableconnections')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipBetweenConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_types', models.CharField(max_length=255)),
                ('relations', models.ManyToManyField(to='class_field.conexs_pool_field')),
            ],
        ),
        migrations.CreateModel(
            name='LinkBetweenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.CharField(max_length=8000)),
                ('link_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_field.relationshipbetweenconnections')),
            ],
        ),
        migrations.CreateModel(
            name='LinkBetweenField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sync_type', models.CharField(max_length=255)),
                ('relation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_field.linkbetweentable')),
            ],
        ),
    ]
